apiVersion: v1
kind: Secret
metadata:
  name: {{ template "self.fullname" . }}-conffiles
  labels:
 {{ include "self.labels" . | indent 4 }}
type: Opaque
data:
{{ (.Files.Glob "conf/*").AsSecrets | indent 2 }}