{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "self.fullname" . }}
  labels:
{{ include "self.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolume.capacity.storage }}
  storageClassName: ""
  selector:
    matchLabels:
      purpose: {{ .Values.persistentVolume.purpose }}
{{- end }}