apiVersion: v1
kind: Secret
metadata:
  name: {{ template "self.fullname" . }}-files
  labels:
 {{ include "self.labels" . | indent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}