# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults_working_directory: &defaults_working_directory
  working_directory: ~/repo

defaults_docker_helm_kube: &defaults_docker_helm_kube
  docker:
    - image: hypnoglow/kubernetes-helm:2.9.1


jobs:
  build:
    <<: *defaults_working_directory
    <<: *defaults_docker_helm_kube
    steps:
      - checkout
      - run: 
          name: Build Chart packages
          command: |
            ./build.sh ./workdir $CIRCLE_TAG
            ./package.sh ./workdir ./wso2-repo/wso2-helm
      # save Chart packages
      - save_cache:
          key: repo-cache-{{ .Branch }}-{{ .Revision }}
          paths: repo

  publish:
    <<: *defaults_working_directory
    machine: true
    #<<: *defaults_docker_helm_kube
    steps:
      - checkout
      - run: 
          name: Checkout gh-pages branch
          command: git fetch origin gh-pages:refs/remotes/origin/gh-pages && git checkout origin gh-pages
      - restore_cache:
          keys: repo-cache-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: Murge origin master into gh-pages branch
          command: git pull origin master
      - run: 
          name: Add repo to gh-pages branch
          command: git add ./wso2-repo
      - run: 
          name: Commit changes to gh-pages branch
          command: git commit -m "Publishing $(date '+%Y%m%d-%H%M%S')"
      - run: 
          name: Publish gh-pages
          command: git push origin    

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)+(\.[0-9]+)$/
            branches:
              only:
                - master
      - publish:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)+(\.[0-9]+)$/
            branches:
              only:
                - master