apiVersion: v1
description: Master Helm chart WSO2 "composite" profile composed by internal API manager and Identity Server
name: wso2-master-int-composite
version: VERSION_PLACEHOLDER
maintainers:
  - name: David Fry
    email: david.fry@modusbox.com
