# requirements.yaml
dependencies:
- name: wso2-is-km
  version: VERSION_PLACEHOLDER
  repository: "file://../wso2-is-km"
  condition: wso2-is-km.enabled
- name: wso2-am-allinone-int
  version: VERSION_PLACEHOLDER
  repository: "file://../wso2-am-allinone-int"
  condition: wso2-am-allinone-int.enabled
