# Default values for wso2am.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
productName: wso2is-km
productVersion: 5.6.0
wso2Home: /home/wso2carbon
wso2amSecretVolPath: /home/wso2carbon/wso2-secret-volume
wso2amConfigVolPath: /home/wso2carbon/wso2-config-volume
wso2amLibVolPath: /home/wso2carbon/wso2-lib-volume
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
image:
  repositoryPath: mojaloop
  tag: DEPLOYMENT_VALUE
  pullPolicy: Always
  dockerImageName: wso2iskm
service:
  type: NodePort
  ports:
    wso2:
      name: wso2
      enabled: true
      externalPort: 9443
      internalPort: 31443
      targetPort: 9443
  sessionAffinity: 
    enabled: false
    affinityType: ClientIP
  external:
    enabled: true
  annotations: {}

rbac:
  serviceAccount: wso2svc-account
  enabled: false

config:
  pullSecret: dock-repo-secret
# dependentServices:
#   external-db:
#     name: dnsname for db here
#     pauseTime: 15  
persistentVolume:
  enabled: true
  basePath: /glusterfs
  purpose: wso2-is-km-shared-artifacts
  mountToSubPath: repository/deployment/server
  capacity: 
    storage: 5Gi
  fsowner:
    userid: "802"
    groupid: "802" 

readinessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 15
  failureThreshold: 5

livenessProbe:
  enabled: true
  initialDelaySeconds: 360
  periodSeconds: 15
  failureThreshold: 5

copyExtHostToEtcHosts:
  enabled: false
  extHostName: wso2exthostname

ingress:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: 3Gi
    cpu: 3000m
  requests:
    memory: 2Gi
    cpu: 2000m

nodeSelector: {}

tolerations: []

affinity: {}
